name: Documentation

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: build-documentation
        uses: ./

      - name: Create doc redirect
        uses: "finnp/create-file-action@master"
        env:
            FILE_NAME: ${{ github.workspace }}/built_documentation.nojekyll
            FILE_DATA: ""

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/built_documentation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to get a token
          MESSAGE: "Build documentation: ({sha}) {msg}"
